@create_repertories.sql
@create_repertories_log.sql
@f_bde_drop_tables.sql
@f_bde_drop_tables_log.sql
@f_bde_catalogue_view.sql
@f_bde_catalogue_view_log.sql
@f_bde_departements.sql
@f_bde_departements_log.sql
@f_bde_marketing.sql
@f_bde_marketing_log.sql
@f_bde_catalogue.sql
@f_bde_catalogue_log.sql