CREATE TABLE f_bde_dataCSV(
	ticket VARCHAR2(10),
	dateTicket VARCHAR2(10),
	ISBN VARCHAR2(20),
	magasin VARCHAR2(10)
)
ORGANIZATION EXTERNAL(
	TYPE ORACLE_LOADER
	DEFAULT DIRECTORY monRepertoireFSrc18
	ACCESS PARAMETERS(
		RECORDS DELIMITED BY newline
		SKIP 0
		CHARACTERSET UTF8
		BADFILE monRepertoireFLog18:'dataCSV.txt.bad'
		LOGFILE monRepertoireFLog18:'dataCSV.txt.log'
		FIELDS TERMINATED BY ';'
		OPTIONALLY ENCLOSED BY '"'
	)
	LOCATION ('Fantastic')
)
REJECT LIMIT 1000;

-- DESCRIBE f_bde_dataCSV;
-- SELECT TABLE_NAME, TYPE_NAME, DEFAULT_DIRECTORY_NAME FROM USER_EXTERNAL_TABLES;